server:
  port: 21015
spring:
  application:
    name: sharding-jdbc-demo
  #环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
  shardingsphere:
    datasource:
      names: mysql
      mysql:
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/shardingDemo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    sharding:
      tables:
        orders:
          table-strategy:
            complex:
              sharding-columns: create_time,order_status,product_name,buyer_name,link_name
              algorithm-class-name: com.dmqwl.data.config.OrdersShardingAlgorithm
          actual-data-nodes: mysql.orders_${['2017_2019','error','free','2020','2021','2022','2023','2024','2025']}


datasource:
  oracle:
    username: 12
    password: 121
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl


logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.demo.sharding.demo.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: ignored
      #驼峰下划线转换
      column-underline: true
      #db-type: mysql
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true




